imports:
  - org/apache/shardingsphere/proxy/frontend/netty/FrontendChannelInboundHandler
  - io/netty/channel/ChannelHandlerContext
  - org/apache/shardingsphere/proxy/frontend/command/CommandExecutorTask
  - org/apache/shardingsphere/proxy/backend/communication/jdbc/transaction/BackendTransactionManager
  - org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLComQueryPacketExecutor
  - org/apache/shardingsphere/proxy/backend/response/query/QueryResponse
  - org/apache/shardingsphere/proxy/backend/response/update/UpdateResponse
  - org/apache/shardingsphere/db/protocol/mysql/packet/generic/MySQLOKPacket
  - java/lang/Object
  - java/lang/String
  - java/util/Collection

metrics:
  FrontendChannelInboundHandler.channelActive(LChannelHandlerContext;)V:
    - type: GAUGE
      name: channel_count
      doc: netty channel count
  FrontendChannelInboundHandler.channelInactive(LChannelHandlerContext;)V:
    - type: GAUGE
      name: channel_count
      method: gaugeDec
      doc: netty channel count
  FrontendChannelInboundHandler.channelRead(LChannelHandlerContext;LObject;)V:
    - type: COUNTER
      name: request_total
      doc: request count total
  CommandExecutorTask.run()V:
    - type: HISTOGRAM
      name: requests_latency_histogram_millis
      doc: request latency histogram millis
  BackendTransactionManager.commit()V:
    - type: COUNTER
      name: transaction_commit_total
      doc: transaction commit total
  BackendTransactionManager.rollback()V:
    - type: COUNTER
      name: transaction_rollback_total
      doc: transaction rollback total
  MySQLComQueryPacketExecutor.createQueryPackets(LQueryResponse;)LCollection;:
    - type: COUNTER
      name: sql_statement_count
      doc: the sql statement count
      labels: ['sql_type:select']
  MySQLComQueryPacketExecutor.createUpdatePacket(LUpdateResponse;)LMySQLOKPacket;:
    - type: COUNTER
      name: sql_statement_count
      doc: the sql statement count
      labels: ['sql_type:$0.type']

configMap:
  jvmEnabled: true
  port : 8091
  host:

debugger:
  debug: true
  outPath: